server:
  port: 9999
spring:
  application:
    name: VitaminCode_BE
  datasource:
    # Fixed in v1.3.3. Doesn't work with mariadb-connector-j v1.3.2 (CONJ-227)
      url: jdbc:mariadb://localhost:3307/vitamincode_class
      # If some of the hosts is down, app won't launch. v1.3.3
      #url: jdbc:mariadb:failover://192.168.33.11:3306,192.168.33.12:3306,192.168.33.13:3306/test?autoReconnect=true
      # Works with mariadb-connector-j v1.3.2
      #url: jdbc:mysql:failover://192.168.33.11:3306/test
      username: root
      password: root123
      driver-class-name: org.mariadb.jdbc.Driver
mybatis:
  config-location: classpath:/static/mybatis/mybatis-config.xml
  mapper-locations: classpath:/static/mybatis/mapper/*.xml

# File hệ thống. - Quan trọng